#AndroidIDE: enforce UTF-8 & locale for Gradle daemon
#Sat Jun 06 14:16:02 GMT 2026
android.nonTransitiveRClass=false
systemProp.user.language=en
systemProp.user.country=US
org.gradle.daemon=true
org.gradle.parallel=false
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding\=UTF-8 -Dsun.jnu.encoding\=UTF-8 -Duser.language\=en -Duser.country\=US
android.useAndroidX=true
android.enableJetifier=true
android.suppressUnsupportedCompileSdk=34
systemProp.sun.jnu.encoding=UTF-8
android.enableResourceOptimizations=false
systemProp.file.encoding=UTF-8
android.disableResourceValidation=false
android.aapt2FromMavenOverride=/data/user/0/com.itsaky.androidide/files/home/.androidide/aapt2
